In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import pandas as pd

In [3]:
dfsup = pd.read_csv('semi_labeled.csv')

In [4]:
dfsup.head()

0  1  2  3  4  5  6  7  8  9  ...  491  492  493  494  495  496  497  498  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   499  Target  
0    0       2  
1    0       1  
2    0       0  
3    0       0  
4    0       0  

[5 rows x 501 columns]

In [5]:
dfsup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544 entries, 0 to 543
Columns: 501 entries, 0 to Target
dtypes: int64(501)
memory usage: 2.1 MB


In [6]:
dfsup.Target.unique()

array([2, 1, 0, 3], dtype=int64)

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
X = dfsup.drop(['Target'],axis=1)

In [9]:
y = dfsup.Target

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42, stratify=y)

In [12]:
model = RandomForestClassifier()

In [13]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [14]:
y_pred = model.predict(X_test)

In [15]:
model.score(X_test,y_test)

0.95

In [16]:
import sklearn.metrics as sm

In [17]:
sm.confusion_matrix(y_test, y_pred)

array([[44,  0,  1,  0],
       [ 0, 43,  1,  1],
       [ 1,  2, 41,  1],
       [ 0,  2,  0, 43]], dtype=int64)

In [18]:
dfun = pd.read_csv('semi_no_label.csv')

In [19]:
dfun.head()

0  1  2  3  4  5  6  7  8    9  ...  490  491  492  493  494  495  496  \
0  0  0  0  0  0  0  0  0  0    0  ...    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0    0  ...    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  212  ...    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0    0  ...    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0    0  ...    0    0    0    0    0    0    0   

   497  498  499  
0    0    0    0  
1    0    0    0  
2    0    0    0  
3    0    0    0  
4    0    0    0  

[5 rows x 500 columns]

In [20]:
dfun.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1950 entries, 0 to 1949
Columns: 500 entries, 0 to 499
dtypes: int64(500)
memory usage: 7.4 MB


In [21]:
from sklearn.cluster import KMeans

In [22]:
model = KMeans(n_clusters=4)

In [23]:
model.fit(dfun)

KMeans(n_clusters=4)

In [24]:
dfsup['cl'] = model.predict( dfsup.drop(['Target'], axis=1 ) )

In [25]:
dfsup.head(10)

0  1  2  3  4  5  6  7  8  9  ...  492  493  494  495  496  497  498  499  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
5  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
6  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
7  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
8  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
9  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   Target  cl  
0       2   3  
1       1   2  
2       0   1  
3       0   3  
4       0   1  
5       0   1  
6       3   0  
7       1   2  
8       3   0  
9       3   0  

[10 rows x 502 columns]

In [26]:
pd.crosstab( dfsup.Target , dfsup.cl )

cl        0    1    2    3
Target                    
0         9  121    0    6
1         3    0  131    2
2        14    1   16  105
3       120    1    6    9

In [27]:
dfun['Target'] = model.labels_

In [28]:
dfun.head()

0  1  2  3  4  5  6  7  8    9  ...  491  492  493  494  495  496  497  \
0  0  0  0  0  0  0  0  0  0    0  ...    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0    0  ...    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  212  ...    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0    0  ...    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0    0  ...    0    0    0    0    0    0    0   

   498  499  Target  
0    0    0       2  
1    0    0       3  
2    0    0       3  
3    0    0       2  
4    0    0       2  

[5 rows x 501 columns]

In [29]:
model = RandomForestClassifier()

In [30]:
X_train = dfun.drop(['Target'],axis=1)

In [31]:
y_train = dfun.Target

In [32]:
X_test = dfsup.drop(['Target','cl'],axis=1)

In [33]:
y_test = dfsup.Target

In [34]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [35]:
y_pred = model.predict(X_test)

In [36]:
model.score(X_test,y_test)

0.04411764705882353

In [37]:
sm.confusion_matrix(y_test, y_pred)

array([[  7, 124,   0,   5],
       [  2,   0, 132,   2],
       [ 17,   2,   8, 109],
       [123,   0,   4,   9]], dtype=int64)